apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vim
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/skabashn-tenant/rpm-build/vim@sha256:c5b9b74ad8548e3bb8a774c1e8eddea4ee3ca107341c91ec10510fa2ffb44735
        name: container-image
        resources: {}
status: {}
