apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vim
    app.kubernetes.io/part-of: rpm-build
  name: vimnlpz
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vim
    weight: 100
status: {}
