apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vim
    app.kubernetes.io/part-of: rpm-build
  name: vim
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: vim
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vim
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/skabashn-tenant/rpm-build/vim@sha256:2c7776cae57f83baa9f0831c484e3c25c673fd600c498be1c81b8faa3ed8ebc2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
